### ISSUE TITLE
ST7262 and version 1.6.1 Not working but 1.6.0 does!

### ISSUE THREAD

**Issue by dagnall53** [moononournation/Arduino_GFX#723]
After finding ST7262 hidden (!) I managed to get it working with : Esp32 V 2.0.17  - I had been looking for a non existent initiation sequence. -Not needed for ST7262. 
I was am using Wavshare ESP32-S3-Touch-LCD-4.3B (BOXED version) (Wiki link below). and the setup in the attached zip file that may be helpful for other users. 

**But when I 'upgraded to Version 1.6.1  I get Compile errors shown below :**
Hopefully you can fix this for other users.. I will stick to 1.6.0 for now!!

Huge thanks. 

ERRORS ON COMPILE...  -- 
 `C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp: In member function 'uint16_t* Arduino_ESP32RGBPanel::getFrameBuffer(int16_t, int16_t)':
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:147:3: error: 'esp_rgb_panel_t' was not declared in this scope
   esp_rgb_panel_t *_rgb_panel;
   ^~~~~~~~~~~~~~~
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:147:3: note: suggested alternative: 'esp_lcd_panel_t'
   esp_rgb_panel_t *_rgb_panel;
   ^~~~~~~~~~~~~~~
   esp_lcd_panel_t
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:147:20: error: '_rgb_panel' was not declared in this scope
   esp_rgb_panel_t *_rgb_panel;
                    ^~~~~~~~~~
In file included from c:\users\dagna\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32s3-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\sys-include\stdio.h:35,
                 from C:\Users\dagna\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\cores\esp32/Arduino.h:27,
                 from C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src/Arduino_DataBus.h:8,
                 from C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.h:18,
                 from C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:3:
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:148:16: error: expected primary-expression before 'const'
   _rgb_panel = __containerof(_panel_handle, esp_rgb_panel_t, base);
                ^~~~~~~~~~~~~
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:148:16: error: expected primary-expression before ')' token
   _rgb_panel = __containerof(_panel_handle, esp_rgb_panel_t, base);
                ^~~~~~~~~~~~~
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:148:16: error: expected primary-expression before ')' token
   _rgb_panel = __containerof(_panel_handle, esp_rgb_panel_t, base);
                ^~~~~~~~~~~~~
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:148:16: error: expected primary-expression before 'const'
   _rgb_panel = __containerof(_panel_handle, esp_rgb_panel_t, base);
                ^~~~~~~~~~~~~
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:148:16: error: '__x' was not declared in this scope
   _rgb_panel = __containerof(_panel_handle, esp_rgb_panel_t, base);
                ^~~~~~~~~~~~~
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:148:16: note: suggested alternative: '__tm'
C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\GFX_Library_for_Arduino\src\databus\Arduino_ESP32RGBPanel.cpp:148:45: error: 'esp_rgb_panel_t' does not name a type; did you mean 'esp_lcd_panel_t'?
   _rgb_panel = __containerof(_panel_handle, esp_rgb_panel_t, base);
                                             ^~~~~~~~~~~~~~~
Multiple libraries were found for "SD.h"
  Used: C:\Users\dagna\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\libraries\SD
  Not used: C:\Users\dagna\AppData\Local\Arduino15\libraries\SD
  Not used: C:\Users\dagna\OneDrive\DocOneDrive\Arduino\libraries\SD
exit status 1

Compilation error: exit status 1`

-

[WAV_4.3inch.zip](https://github.com/user-attachments/files/22426266/WAV_4.3inch.zip)

https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3B
