### ISSUE TITLE
Compilation error with ESP32-S3 with latest 1.5.2 and master 

### ISSUE THREAD

**Issue by milGus** [moononournation/Arduino_GFX#610]
Hi
Trying to compile on ESP32-S3 in arduino IDE 2.2 with arduino_esp32 v3.0.0 onwards.

/Arduino32/libraries/Arduino_GFX-master-20250116/src/databus/Arduino_ESP32QSPI.cpp: In member function 'virtual bool Arduino_ESP32QSPI::begin(int32_t, int8_t)':
/Arduino32/libraries/Arduino_GFX-master-20250116/src/databus/Arduino_ESP32QSPI.cpp:59:21: error: 'ESP_INTR_CPU_AFFINITY_AUTO' was not declared in this scope
   59 |       .isr_cpu_id = ESP_INTR_CPU_AFFINITY_AUTO,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

Any ideas?

**Comment by milGus** [comment]
OK thats a good idea. Yes that is working fine. Thankyou for your great work.
